add search button and link it to function
NitinNair89/TheHungryRecipes pull request #5
Opened 2019-10-05 19:06 UTC by alexresiga

#4

2019-10-05 19:15 UTC, NitinNair89 commented
Thanks! Can you setup a GitHub page pointing to your fork repo's master branch so that I can view the UI with your code changes?

2019-10-05 19:54 UTC, alexresiga commented
https://alexresiga.github.io/TheHungryRecipes/index.html

2019-10-06 05:57 UTC, NitinNair89 requested changes
> https://alexresiga.github.io/TheHungryRecipes/index.html

The interface is broken. Please make the below changes:
- "Search Recipe" should be the button text and position it below the "Random Recipe" button
- Add the chef hat icon to the search recipe button
- Do not change the grid column size, keep it as-is

![FireShot Capture 004 - The Hungry Recipes - alexresiga github io](https://user-images.githubusercontent.com/16149618/66264965-29436b00-e82c-11e9-8008-015ff51c94c5.png)

2019-10-06 05:57 UTC, NitinNair89 commented on index.html
> +                          <div class="four columns">
Let's not change the grid column size

2019-10-06 05:57 UTC, NitinNair89 commented on index.html
> +                          <div class="eight columns" style="position:relative;" id="randomMealBtnContainer">
Let's not change the grid column size

2019-10-06 09:09 UTC, alexresiga commented on index.html
> +                          <div class="four columns">
solved see new commit

2019-10-06 10:00 UTC, NitinNair89 requested changes
I checked the live site on the link you previously shared. The alignment seems a little off. Let's do it this way:
- Create a row inside the eight columns div similar to the structure made for the input field
- Keep the chef hat icon for the random recipe button

2019-10-06 10:10 UTC, alexresiga commented
> I checked the live site on the link you previously shared. The alignment seems a little off. Let's do it this way:

the alignment is a bit off because the buttons don't have a fixed width they expand with the text inside them

> * Create a row inside the eight columns div similar to the structure made for the input field

i don't understand what you mean by this
> * Keep the chef hat icon for the random recipe button

ok

2019-10-06 10:20 UTC, NitinNair89 commented
> i don't understand what you mean by this

Currently, the <h4> is floating and occupies full width of its container. We can create a row class div with the same structure as for input field

**Current code:**
`<h4>Confused what to cook? <br/><small>Search a recipe or try a random recipe!</small></h4>`

**Suggestion:**
```
<div class="row">
  <div class="eight columns">
    <h4>Confused what to cook? <br/><small>Search a recipe or try a random recipe!</small></h4>
  </div>
  <div class="four columns">
      Random Recipe button
  </div>
</div>
```
Can you give this a try and see if it solves alignment issues? :slightly_smiling_face:

2019-10-06 10:32 UTC, NitinNair89 commented
Have you tested everything?

2019-10-06 10:33 UTC, alexresiga commented
yes, you can see oh the gh pages link

2019-10-06 12:15 UTC, NitinNair89 commented
> yes, you can see oh the gh pages link

Looks fine. There's a bug, I will open a separate issue and assign it to you. Is that fine?

2019-10-06 12:17 UTC, merged

2019-10-06 12:24 UTC, NitinNair89 commented
Closes #4

2019-10-06 13:31 UTC, alexresiga commented
> Looks fine. There's a bug, I will open a separate issue and assign it to you. Is that fine?

sure